'use client'

import { useTransition } from 'react'
import { updateLeadStatus } from '@/app/inbox/actions'

type Lead = { id: string; created_at: string; intent: string; budget_aed: number | null; timeline: string; area: string; name: string; phone: string; notes: string | null; lang: string; score: number | null; band: string | null; ai_summary: string | null; next_action: string | null; status: string }

export function InboxTable({ leads, signedIn }: { leads: Lead[]; signedIn: boolean }) {
  const [pending, startTransition] = useTransition()
  if (!signedIn) return <main className="min-h-screen bg-slate-950 px-6 py-20 text-center text-white"><p className="text-sm uppercase tracking-[0.2em] text-emerald-400">Agent inbox</p><h1 className="mt-5 text-4xl font-semibold">Sign in to view leads</h1><p className="mx-auto mt-4 max-w-md text-slate-400">Lead data is protected and only available to authenticated agents.</p></main>
  return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white sm:px-10"><div className="mx-auto max-w-7xl"><div className="mb-8 flex items-end justify-between"><div><p className="text-sm uppercase tracking-[0.2em] text-emerald-400">Agent inbox</p><h1 className="mt-2 text-3xl font-semibold">Qualified leads</h1></div><span className="rounded-full bg-white/10 px-3 py-1 text-sm text-slate-300">{leads.length} leads</span></div><div className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.04]"><div className="divide-y divide-white/10">{leads.map((lead) => <article key={lead.id} className="grid gap-4 p-5 md:grid-cols-[1.2fr_1fr_1fr_1fr_auto] md:items-center"><div><div className="flex items-center gap-2"><h2 className="font-semibold">{lead.name}</h2><span className={`rounded-full px-2 py-0.5 text-xs font-bold uppercase ${lead.band === 'hot' ? 'bg-red-400/15 text-red-300' : lead.band === 'warm' ? 'bg-amber-400/15 text-amber-300' : 'bg-slate-400/15 text-slate-300'}`}>{lead.band}</span></div><p className="mt-1 text-sm text-slate-400">{lead.phone} · {lead.area}</p></div><div><p className="text-xs uppercase text-slate-500">Intent</p><p className="mt-1 capitalize">{lead.intent} · AED {lead.budget_aed?.toLocaleString()}</p></div><div><p className="text-xs uppercase text-slate-500">Timeline</p><p className="mt-1">{lead.timeline}</p></div><div><p className="text-xs uppercase text-slate-500">Next action</p><p className="mt-1 text-sm text-slate-300">{lead.next_action ?? 'Review lead'}</p></div><select aria-label={`Status for ${lead.name}`} disabled={pending} value={lead.status} onChange={(e) => startTransition(() => { void updateLeadStatus(lead.id, e.target.value as 'new' | 'contacted' | 'viewing' | 'closed') })} className="rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-sm"><option>new</option><option>contacted</option><option>viewing</option><option>closed</option></select>{lead.notes && <p className="md:col-span-5 text-sm text-slate-400">{lead.notes}</p>}</article>)}{leads.length === 0 && <p className="p-10 text-center text-slate-400">No leads available.</p>}</div></div></div></main>
}
