'use client'

import { useMemo, useState, useTransition } from 'react'
import { updateLeadStatus } from '@/app/inbox/actions'

type Lead = { id: string; created_at: string; intent: string; budget_aed: number | null; timeline: string; area: string; name: string; phone: string; notes: string | null; lang: string; score: number | null; band: string | null; reasons: string[] | null; ai_summary: string | null; next_action: string | null; status: string }

const bandStyles: Record<string, string> = { hot: 'bg-red-400/15 text-red-300', warm: 'bg-amber-400/15 text-amber-300', cold: 'bg-slate-400/15 text-slate-300' }
const label = (value: string) => value.replace('offplan', 'off-plan investor').replace('1-3m', '1–3 months').replace('3-6m', '3–6 months').replace('6m+', '6+ months')

export function InboxTable({ leads }: { leads: Lead[] }) {
  const [filter, setFilter] = useState('all')
  const [search, setSearch] = useState('')
  const [selected, setSelected] = useState<Lead | null>(null)
  const [pending, startTransition] = useTransition()
  const visible = useMemo(() => leads.filter((lead) => (filter === 'all' || lead.band === filter) && `${lead.name} ${lead.area}`.toLowerCase().includes(search.toLowerCase())), [leads, filter, search])
  const stats = useMemo(() => ({ total: leads.length, hot: leads.filter((l) => l.band === 'hot').length, warm: leads.filter((l) => l.band === 'warm').length, cold: leads.filter((l) => l.band === 'cold').length, recent: leads.filter((l) => Date.now() - new Date(l.created_at).getTime() <= 7 * 86400000).length, average: leads.length ? Math.round(leads.reduce((sum, l) => sum + (l.budget_aed ?? 0), 0) / leads.length) : 0 }), [leads])
  const statusChange = (lead: Lead, status: string) => startTransition(() => { void updateLeadStatus(lead.id, status as 'new' | 'contacted' | 'viewing' | 'closed') })

  return <main className="min-h-screen bg-slate-950 px-5 py-8 text-white sm:px-10"><div className="mx-auto max-w-7xl"><header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm uppercase tracking-[0.2em] text-emerald-400">Agent inbox</p><h1 className="mt-2 text-3xl font-semibold">Qualified leads</h1></div><span className="rounded-full bg-white/10 px-3 py-1 text-sm text-slate-300">{stats.total} leads</span></header>
    <section aria-label="Lead statistics" className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{[['Total', stats.total], ['Hot', stats.hot], ['Warm', stats.warm], ['Cold', stats.cold], ['Last 7 days', stats.recent], ['Avg budget', `AED ${stats.average.toLocaleString()}`]].map(([name, value]) => <div key={String(name)} className="rounded-xl border border-white/10 bg-white/[0.04] p-4"><p className="text-xs uppercase tracking-wide text-slate-500">{name}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>)}</section>
    <div className="mb-5 flex flex-col gap-3 sm:flex-row"><input aria-label="Search leads" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search name or area" className="min-h-11 flex-1 rounded-xl border border-white/10 bg-white/[0.06] px-4 text-sm outline-none placeholder:text-slate-500 focus:border-emerald-400" /><div className="flex rounded-xl border border-white/10 bg-white/[0.04] p-1">{['all', 'hot', 'warm', 'cold'].map((band) => <button key={band} type="button" onClick={() => setFilter(band)} className={`rounded-lg px-3 py-2 text-sm capitalize ${filter === band ? 'bg-emerald-400 text-slate-950' : 'text-slate-400'}`}>{band}</button>)}</div></div>
    <section className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.04]"><div className="divide-y divide-white/10">{visible.map((lead) => <article key={lead.id} onClick={() => setSelected(lead)} className="grid cursor-pointer gap-4 p-5 transition hover:bg-white/[0.05] md:grid-cols-[1.2fr_1fr_1fr_1fr_auto] md:items-center"><div><div className="flex items-center gap-2"><h2 className="font-semibold">{lead.name}</h2><span className={`rounded-full px-2 py-0.5 text-xs font-bold uppercase ${bandStyles[lead.band ?? 'cold']}`}>{lead.band}</span></div><p className="mt-1 text-sm text-slate-400">{lead.phone} · {lead.area}</p></div><div><p className="text-xs uppercase text-slate-500">Intent</p><p className="mt-1 capitalize">{label(lead.intent)} · AED {(lead.budget_aed ?? 0).toLocaleString()}</p></div><div><p className="text-xs uppercase text-slate-500">Timeline</p><p className="mt-1">{label(lead.timeline)}</p></div><div><p className="text-xs uppercase text-slate-500">Next action</p><p className="mt-1 text-sm text-slate-300">{lead.next_action ?? 'Review lead'}</p></div><select aria-label={`Status for ${lead.name}`} disabled={pending} value={lead.status} onClick={(e) => e.stopPropagation()} onChange={(e) => statusChange(lead, e.target.value)} className="rounded-lg border border-white/10 bg-slate-900 px-3 py-2 text-sm"><option>new</option><option>contacted</option><option>viewing</option><option>closed</option></select></article>)}{visible.length === 0 && <p className="p-10 text-center text-slate-400">No leads match your filters.</p>}</div></section>
    {selected && <div role="dialog" aria-modal="true" aria-label={`Lead details for ${selected.name}`} className="fixed inset-0 z-10 flex items-end justify-center bg-slate-950/80 p-4 sm:items-center" onClick={() => setSelected(null)}><div className="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-white/10 bg-slate-900 p-6 shadow-2xl" onClick={(e) => e.stopPropagation()}><div className="flex items-start justify-between gap-4"><div><p className="text-sm text-emerald-400">Lead details</p><h2 className="mt-1 text-2xl font-semibold">{selected.name}</h2></div><button type="button" onClick={() => setSelected(null)} className="rounded-lg px-3 py-2 text-slate-400 hover:bg-white/10">Close</button></div><div className="mt-6 grid gap-4 sm:grid-cols-2">{[['Intent', label(selected.intent)], ['Budget', `AED ${(selected.budget_aed ?? 0).toLocaleString()}`], ['Timeline', label(selected.timeline)], ['Area', selected.area], ['Phone', selected.phone], ['Language', selected.lang.toUpperCase()], ['Status', selected.status], ['Score band', selected.band ?? '—']].map(([key, value]) => <div key={key}><p className="text-xs uppercase tracking-wide text-slate-500">{key}</p><p className="mt-1">{value}</p></div>)}</div>{selected.notes && <div className="mt-6"><p className="text-xs uppercase tracking-wide text-slate-500">Notes</p><p className="mt-2 whitespace-pre-wrap text-slate-300">{selected.notes}</p></div>}<div className="mt-6"><p className="text-xs uppercase tracking-wide text-slate-500">Score reasons</p><ul className="mt-2 list-disc space-y-1 pl-5 text-slate-300">{(selected.reasons ?? []).map((reason, index) => <li key={`${reason}-${index}`}>{reason}</li>)}</ul></div><div className="mt-6 grid gap-4 sm:grid-cols-2"><div><p className="text-xs uppercase tracking-wide text-slate-500">AI summary</p><p className="mt-2 text-slate-300">{selected.ai_summary ?? 'Not available'}</p></div><div><p className="text-xs uppercase tracking-wide text-slate-500">Next action</p><p className="mt-2 text-slate-300">{selected.next_action ?? 'Not available'}</p></div></div></div></div>}
  </div></main>
}

export type { Lead }

export function sortLeads(leads: Lead[]) { const rank: Record<string, number> = { hot: 0, warm: 1, cold: 2 }; return [...leads].sort((a, b) => (rank[a.band ?? 'cold'] - rank[b.band ?? 'cold']) || ((b.score ?? 0) - (a.score ?? 0)) || (new Date(b.created_at).getTime() - new Date(a.created_at).getTime())) }
